apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-troubleshooting-agent.fullname" . }}-gchat
  labels:
    {{- include "k8s-troubleshooting-agent.labels" . | nindent 4 }}
type: Opaque
data:
  service-account-key.json: {{ .Values.secrets.gchat.serviceAccountKey | b64enc | quote }}
